version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
    day: "tuesday"
    time: "01:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  reviewers:
  - romainmenke
  - fd
  versioning-strategy: increase
  rebase-strategy: disabled
  groups:
    all-dependencies:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: "tuesday"
    time: "01:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  rebase-strategy: disabled
  reviewers:
  - romainmenke
  - fd
  groups:
    all-dependencies:
      patterns:
        - "*"
  ignore:
  - dependency-name: "cloudflare/wrangler-action"
    update-types: ["version-update:semver-major"]
- package-ecosystem: "gomod"
  directory: "/"
  open-pull-requests-limit: 10
  labels:
    - "go"
    - "dependencies"
  schedule:
    interval: weekly
    day: "tuesday"
    time: "01:00"
    timezone: Europe/Brussels
  groups:
    all-dependencies:
      patterns:
        - "*"
