language: node_js
node_js:
  - node
install:
  - make install
  - make generate
script:
  - make build-example
  - make build-tests
  - make run-tests
env:
  global:
    - BROWSERSTACK_USERNAME=simonmenke
    - secure: "ex9A3gs2B8j57uPlv9aKsQHRIZY8WdBq7XbCm96wPfxJed2UzOg211odayHvcmVAt4n3CSpyxolF1tvEIihWHHHF6jR8yDuK5kaXiRkIPFFeNprTKbkGs+745Gyb1xnp8PGgLdZLi8JWU2dJWUEFEeMYmIXskKXHtn+mJe15fdNbus1zhjHcWv+T3V6jkROoDRShzq56UgiQC7/wpiOCGtS6kn92en4OY7JUAQHGUFJT1ldVGm+/vZt+dbd5y2ME1HTduZw4ml+H4YZuImdTEZhiBSCZKUC8hOpn1tYn913xfgiaCol5WHjplnRhjV+ukNgdCy6rZqwzJYWEbNOk2AdzLOKD8ykjIafzyXUAbDPH4016almquaHK8zMdjQfBsi0mp6EiqHLal4SGcAKr82yupRckI8amJyn8BwamDh7zufVMoq1ell6irm48NAw0lYZLRG5qedB0HPX5tD3fpxHe1ZNTqUtMcVlBhDEEG6D2pcFTWYepOT6q+ldcbL1QcbwmgCdNmJVe+7G/JmUClQG9WdUHmlQ9DqvMkjmxs0+OhgVq2IqoHd6Gcxk4RN5NtK649ZidXRKIk9El4VbO0RM4qmApKuWjzOXMjNuRQHn7po6kNKSmp38elNwwLMOo+h5cEB2VFoODdRwxdaZEdPyHzF76ISpgBCbaxZ4Es1I="
